services:
  test_db:
    image: postgres:14.0-alpine
    container_name: test_paymentdb
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=adminlol
    ports:
      - "5433:5432"
    command: ["postgres", "-c", "log_statement=all"]